[general]
ipc_socket = false

[window]
padding = { x = 8, y = 3 }
decorations = "None"
decorations_theme_variant = "None"
opacity = 0.79
class = { instance = "alacritty", general = "alacritty" }

[font]
normal = { style = "Bold" }
size = 13
builtin_box_drawing = true

[cursor]
style = { shape = "Beam" }
unfocused_hollow = true
thickness = 0.15

[terminal]
osc52 = "CopyPaste"

[hints]
alphabet = "abcdefghijklmnopqrstuvwxyz;"

[keyboard]
bindings = [
  { key = "F", mods = "Control|Shift", action = "None" },
  { key = "H", mods = "Control|Shift", action = "SearchForward" },
  { key = "D", mods = "Control", mode = "Search", action = "SearchFocusPrevious" },
  { key = "F", mods = "Control", mode = "Search", action = "SearchFocusNext" },
  { key = "D", mods = "Control", mode = "Vi", action = "SearchPrevious" },
  { key = "F", mods = "Control", mode = "Vi", action = "SearchNext" },
  { key = "D", mods = "Control", action = "ScrollLineUp" },
  { key = "F", mods = "Control", action = "ScrollLineDown" },
]

[debug]
prefer_egl = true

[colors.primary]
background = '#252623' # {< replace_color(theme.colors.background) >}
foreground = '#f1e9d2' # {< replace_color(theme.colors.foreground) >}

[colors.normal]
black = '#1c1e1b' # {< replace_color(theme.colors.black) >}
red = '#e75a7c' # {< replace_color(theme.colors.red) >}
green = '#8fb573' # {< replace_color(theme.colors.green) >}
yellow = '#dbb651' # {< replace_color(theme.colors.yellow) >}
blue = '#57a5e5' # {< replace_color(theme.colors.blue) >}
magenta = '#aaaaff' # {< replace_color(theme.colors.magenta) >}
cyan = '#70c2be' # {< replace_color(theme.colors.cyan) >}
white = '#f1e9d2' # {< replace_color(theme.colors.white) >}

[colors.bright]
black = '#5b5e5a' # {< replace_color(theme.colors.bright_black) >}
red = '#e75a7c' # {< replace_color(theme.colors.bright_red) >}
green = '#8fb573' # {< replace_color(theme.colors.bright_green) >}
yellow = '#dbb651' # {< replace_color(theme.colors.bright_yellow) >}
blue = '#57a5e5' # {< replace_color(theme.colors.bright_blue) >}
magenta = '#aaaaff' # {< replace_color(theme.colors.bright_magenta) >}
cyan = '#70c2be' # {< replace_color(theme.colors.bright_cyan) >}
white = '#fff8f0' # {< replace_color(theme.colors.bright_white) >}

