[general]
ipc_socket = false

[window]
padding = { x = 8, y = 0 }
decorations = "None"
decorations_theme_variant = "None"
opacity = 0.69
# blur = true
class = { instance = "alacritty", general = "alacritty" }

[font]
# normal = { style = "Bold" }
size = 13
builtin_box_drawing = true

[cursor]
style = { shape = "Beam" }
vi_mode_style = { shape = "Beam" }
unfocused_hollow = true
thickness = 0.15

[terminal]
osc52 = "CopyPaste"

[hints]
alphabet = "abcdefghijklmnopqrstuvwxyz;"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
binding = { key = "O", mods = "Control|Shift" }
mouse.enabled = false

[keyboard]
bindings = [
  { key = "F", mods = "Control|Shift", mode = "Vi", action = "None" },
  { key = "Space", mods = "Control|Shift", mode = "Vi", action = "None" },
  { key = "Enter", mods = "Control|Shift", mode = "~Search", action = "ToggleViMode" },
  { key = "H", mods = "Control|Shift", action = "SearchForward" },
  { key = "G", mods = "Control", action = "ScrollToTop" },
  { key = "G", mods = "Control|Shift", action = "ScrollToBottom" },
  { key = "N", mods = "Control|Shift", mode = "Search", action = "SearchFocusPrevious" },
  { key = "N", mods = "Control", mode = "Search", action = "SearchFocusNext" },
  { key = "N", mods = "Control|Shift", mode = "Vi", action = "SearchPrevious" },
  { key = "N", mods = "Control", mode = "Vi", action = "SearchNext" },
  { key = "D", mods = "Control", mode = "~AppCursor|~AppKeypad|~Alt", action = "ScrollLineUp" },
  { key = "F", mods = "Control", mode = "~AppCursor|~AppKeypad|~Alt", action = "ScrollLineDown" },
]

[debug]
# prefer_egl = true

[colors.primary]
background = '#001419' # {< replace_color(theme.colors.background) >}
foreground = '#c8d3f5' # {< replace_color(theme.colors.foreground) >}

[colors.normal]
black = '#1b1d2b'   # {< replace_color(theme.colors.black) >}
red = '#ff757f'     # {< replace_color(theme.colors.red) >}
green = '#c3e88d'   # {< replace_color(theme.colors.green) >}
yellow = '#ffc777'  # {< replace_color(theme.colors.yellow) >}
blue = '#82aaff'    # {< replace_color(theme.colors.blue) >}
magenta = '#c099ff' # {< replace_color(theme.colors.magenta) >}
cyan = '#86e1fc'    # {< replace_color(theme.colors.cyan) >}
white = '#828bb8'   # {< replace_color(theme.colors.white) >}

[colors.bright]
black = '#444a73'   # {< replace_color(theme.colors.bright_black) >}
red = '#ff8d94'     # {< replace_color(theme.colors.bright_red) >}
green = '#c7fb6d'   # {< replace_color(theme.colors.bright_green) >}
yellow = '#ffd8ab'  # {< replace_color(theme.colors.bright_yellow) >}
blue = '#9ab8ff'    # {< replace_color(theme.colors.bright_blue) >}
magenta = '#caabff' # {< replace_color(theme.colors.bright_magenta) >}
cyan = '#b2ebff'    # {< replace_color(theme.colors.bright_cyan) >}
white = '#c8d3f5'   # {< replace_color(theme.colors.bright_white) >}
