#!/bin/bash

handle() {
  event=$(echo "${1}" | jq -r keys[0])
  value=$(echo "${1}" | jq .${event})
  # echo "${event}=${value}"
  case "${event}" in
  "WorkspaceActivated")
    workspace_id=$(echo "${value}" | jq ".id")
    eww-workspace change "${workspace_id}"
    eww update applist="$(eww-tools get_app_list)"
    ;;
  "WorkspacesChanged")
    eww-workspace init
    eww update activewindow="$(eww-tools get_activewindow_id)"
    eww update applist="$(eww-tools get_app_list)"
    ;;
  "WorkspaceActiveWindowChanged")
    windowid=$(echo "${value}" | jq ".active_window_id")
    eww update activewindow="${windowid}"
    ;;
  "WindowFocusChanged")
    windowid=$(echo "${value}" | jq ".id")
    eww update activewindow="${windowid}"
    ;;
  "WindowOpened")
    eww update applist="$(eww-tools get_app_list)"
    windowid=$(echo "${value}" | jq ".window.id")
    eww update activewindow="${windowid}"
    ;;
  # "WindowUpdated")
  #   title=$(echo "${value}" | jq ".window.title")
  #   if [[ ${title} =~ "Bitwarden — Zen Browser" ]]; then
  #     id=$(echo "${value}" | jq ".window.id")
  #     niri msg action move-window-to-floating  --id ${id}
  #     niri msg action set-window-width --id ${id} 1280
  #     niri msg action set-window-height --id ${id} 720
  #     niri msg action center-window  --id ${id}
  #   fi
  #   ;;
  "WindowClosed")
    eww update applist="$(eww-tools get_app_list)"
    ;;
  "ConfigLoaded")
    if [[ $(echo "${value}" | jq ".failed") == true ]]; then
      notify-send --app-name=niri-config "ConfigLoaded Falied" "Please Run niri validate for more details."
    fi
    ;;
  "CastStartedOrChanged")
    pid=$(echo "${value}" | jq ".cast.pid")
    name=$(ps -p ${pid} -o comm=)
    record=$(echo "${value}" | jq "{stream_id:.cast.stream_id,pid:.cast.pid,name:\"${name}\"}")
    eww-record start "${record}"
    ;;
  "CastStopped")
    eww-record stop "${value}"
    ;;
  esac
}

niri msg -j event-stream | while read -r line; do handle "$line"; done
