#!/bin/bash

operate=$1
address=$2

special_workspacename=$(eww-tools get_special_workspacename)
activeworkspace_id=$(eww-tools get_activeworkspace_id)

is_minimize() {
  flag=$(hyprctl clients -j | jq ".[] | select(.address==\"${1}\") | .workspace.name==\"${special_workspacename}\"")
  echo "${flag}"
}


minimize() {
  if [[ $(is_minimize "${1}") == true ]]; then
    hyprctl dispatch movetoworkspacesilent ${activeworkspace_id},address:"${1}"
    hyprctl dispatch focuswindow address:"${1}"
  else
    hyprctl dispatch movetoworkspacesilent "${special_workspacename}",address:"${1}"
  fi
  eww update applist="$(eww-tools get_app_list)"
}

reminimize() {
  address=$(eww-tools get_app_list | jq -r "[.[] | select(.minimized==true)] | .[0] | .address")
  echo "${address}"
}

if [[ ${operate} == "minimize" ]]; then
  if [[ ${WAYLAND_COMPOSITOR} == "hypr" ]]; then
    minimize "${address}"
  elif [[ ${WAYLAND_COMPOSITOR} == "niri" ]]; then
    niri msg action focus-window --id "${address}"
  fi
elif [[ ${operate} == "minimizecurrent" ]]; then
  current=$(hyprctl -j activewindow | jq -r ".address")
  minimize "${current}"
elif [[ ${operate} == "reminimize" ]]; then
  current=$(reminimize)
  if [[ ${current} != "null" ]]; then
    minimize "${current}"
    hyprctl dispatch focuswindow address:"${current}"
  fi
elif [[ ${operate} == "isminimize" ]]; then
  is_minimize "${address}"
# elif [[ ${operate} == "get_app_list_once" ]]; then
#   eww update applist="$(eww-tools get_app_list)"
#   if [[ $(eww get applistonce) == true ]]; then
#     eww update applistonce=false
#   fi
fi
