#!/bin/bash

operate=$1

special_workspacename="special:magic"

get_activeworkspace_id() {
  if [[ ${WAYLAND_COMPOSITOR} == "hypr" ]]; then
    echo $(hyprctl activeworkspace -j | jq ".id")
  elif [[ ${WAYLAND_COMPOSITOR} == "niri" ]]; then
    echo $(niri msg -j workspaces | jq ". [] | select(.is_active==true) | .idx")
  fi
}

get_activewindow_id() {
  if [[ ${WAYLAND_COMPOSITOR} == "hypr" ]]; then
    echo $(hyprctl -j activewindow | jq ".address")
  elif [[ ${WAYLAND_COMPOSITOR} == "niri" ]]; then
    echo $(niri msg -j windows | jq ".[] | select(.is_focused==true) | .id")
  fi
}

get_workspaces() {
  if [[ ${WAYLAND_COMPOSITOR} == "hypr" ]]; then
    echo "[1,2,3,4,5,6]"
  elif [[ ${WAYLAND_COMPOSITOR} == "niri" ]]; then
    echo $(niri msg -j workspaces | jq "[.[].idx] | sort")
  fi
}

get_app_list() {
  if [[ ${WAYLAND_COMPOSITOR} == "hypr" ]]; then
    applist=$(hyprctl clients -j | jq "[.[] | .minimized=.workspace.name==\"${special_workspacename}\" | select(.workspace.id==${1} or .workspace.name==\"${special_workspacename}\")] | sort_by(.at)")
  elif [[ ${WAYLAND_COMPOSITOR} == "niri" ]]; then
    workspaceid=$(niri msg -j workspaces | jq ".[] | select(.idx==${1}) | .id")
    applist=$(niri msg -j windows | jq "[.[] | select(.workspace_id==${workspaceid}) | .minimized=false | .class=.app_id |.address=.id] | sort_by(.layout.pos_in_scrolling_layout)")
  fi
  echo "${applist}"
}

if [[ ${operate} == "get_activewindow_id" ]]; then
  get_activewindow_id
elif [[ ${operate} == "get_workspaces" ]]; then
  get_workspaces
elif [[ ${operate} == "get_activeworkspace_id" ]]; then
  get_activeworkspace_id
elif [[ ${operate} == "get_app_list" ]]; then
  get_app_list $(get_activeworkspace_id)
elif [[ ${operate} == "get_special_workspacename" ]]; then
  echo "${special_workspacename}"
fi
