#!/bin/bash

code="export let name = \"${1}\";"

ctl=~/app/wallpaper/wpaperctl

eww-window close platte

if [[ ${1} == "wallpaper" ]]; then
  wallust -q run $("${ctl}" get $("${ctl}" status | jq -R 'split(": ") | .[0]'))
else
  colorscheme=$(yolk eval "write_current_colorscheme(\"${1}\")")
  echo "${colorscheme}" > ~/.config/wallust/colorschemes/terminal.json && wallust -q -T cs terminal
fi

echo "${code}" > ~/.config/yolk/theme.rhai && yolk sync
sleep 1
eww update theme="${1}" && eww-volume once
eww-minimize getAppList
