#!/bin/bash

old_address=""

handle() {
  # if [[ ${1:0:11} == "workspacev2" ]]; then
  #   # workspaceid=${1:13:1}
  #   # eww update activeworkspace="${workspaceid}"
  #   echo $1
  # elif [[ ${1:0:10} == "openwindow" ]]; then
  #   echo $1
  # fi
  echo $1
  case $1 in
  workspacev2*)
    workspaceid=${1:13:1}
    eww-workspace update "${workspaceid}"
    eww update applist="$(eww-tools get_app_list)"
    ;;
  activewindowv2*)
    address="0x${1:16}"
    if [[ ${address} != ${old_address} ]]; then
      eww update activewindow="${address}"
      old_address=${address}
    fi
    ;;
  openwindow*)
    # address="0x${1:12:12}"
    eww update applist="$(eww-tools get_app_list)"
    # eww-minimize capture "${address}"
    ;;
  closewindow*)
    eww update applist="$(eww-tools get_app_list)"
    ;;
  # windowtitlev2*)
  #   address="0x${1:15}"
  #   echo "${address}"
  #   ;;
  esac
}

socat - "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | while read -r line; do handle "$line"; done
