#!/bin/bash

old_address=""

handle() {
  echo $1
  case $1 in
  workspacev2*)
    workspaceid=${1:13:1}
    eww-workspace update "${workspaceid}"
    eww update applist="$(eww-tools get_app_list)"
    ;;
  activewindowv2*)
    address="0x${1:16}"
    if [[ ${address} != ${old_address} ]]; then
      eww update activewindow="${address}"
      old_address=${address}
    fi
    ;;
  openwindow*)
    # address="0x${1:12:12}"
    eww update applist="$(eww-tools get_app_list)"
    # eww-minimize capture "${address}"
    ;;
  closewindow*)
    eww update applist="$(eww-tools get_app_list)"
    ;;
  # windowtitlev2*)
  #   address="0x${1:15:12}"
  #   title="${1:28}"
  #   if [[ ${address} != ${old_address1} ]]; then
  #     if [[ ${title} =~ "Bitwarden Password Manager" ]]; then
  #       hyprctl dispatch "hl.dsp.window.float({ window = \"address:${address}\" })"
  #       old_address1=${address}
  #     fi
  #   fi
  #   ;;
  esac
}

socat - "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | while read -r line; do handle "$line"; done
