#!/bin/bash

operate=$1
number=$2

if [[ ${WAYLAND_COMPOSITOR} == "hypr" ]]; then
  if [[ ${operate} == "change" ]]; then
    hyprctl dispatch workspace "${number}"
  fi
elif [[ ${WAYLAND_COMPOSITOR} == "niri" ]]; then
  workspaces_info=$(niri msg -j workspaces)
  if [[ ${operate} == "change" ]]; then
    number=$(echo "${workspaces_info}" | jq ".[] | select(.id==${number}) | .idx")
  elif [[ ${operate} == "init" ]]; then
    workspaces=$(echo "${workspaces_info}" | jq "[.[].idx] | sort")
    eww update workspaces="${workspaces}"
    number=$(echo "${workspaces_info}" | jq ".[] | select(.is_active==true) | .idx")
  fi
fi

eww update activeworkspace="${number}"
