#!/bin/bash

width=$1
height=$2

if [[ ${WAYLAND_COMPOSITOR} == "niri" ]]; then
  niri msg action set-window-width ${width}
  sleep 0.1
  niri msg action center-window
elif [[ ${WAYLAND_COMPOSITOR} == "hypr" ]]; then
  hyprctl dispatch "hl.dsp.window.resize({ x = \"${width}\", y = \"${height}\"})"
  hyprctl dispatch "hl.dsp.window.center()"
fi
