tabs = false
idle = true
fork = false
frame = "none"

[font]
# normal = ["monospace", "Apple Color Emoji", "LXGW WenKai Mono GB Screen"]
normal = ["monospace", "Twemoji Mozilla", "LXGW WenKai Mono GB Screen"]
size = 13

[box-drawing]
mode = "native"

[box-drawing.sizes]
default = [1, 3]
