font=monospace:size=13
pad=8x0
box-drawings-uses-font-glyphs=no

[tweak]
overflowing-glyphs=no
# render-timer=osd

[scrollback]
lines=10000
# multiplier=20.0
indicator-position=none

[cursor]
style=Beam
beam-thickness=1.2

[key-bindings]
search-start=Control+Shift+h
scrollback-up-line=Control+d 
scrollback-down-line=Control+f
# scrollback-down-line=Control+f Control+Shift+f

[search-bindings]
cursor-left=Left Control+h
cursor-right=Right Control+l
find-prev=Control+Shift+n
find-next=Control+n

[url]
launch=handlr open ${url}
label-letters=abcdefghijklmnopqrstuvwxyz;,.[]

[colors-dark]
# blur=true
cursor=111111 839395 
alpha=0.69
# {# replace_color_foot(theme.colors.background) #}
background=001419
# {# replace_color_foot(theme.colors.foreground) #}
foreground=c8d3f5
# {# replace_color_foot(theme.colors.black) #}
regular0=1b1d2b
# {# replace_color_foot(theme.colors.red) #}
regular1=ff757f
# {# replace_color_foot(theme.colors.green) #}
regular2=c3e88d
# {# replace_color_foot(theme.colors.yellow) #}
regular3=ffc777
# {# replace_color_foot(theme.colors.blue) #}
regular4=82aaff
# {# replace_color_foot(theme.colors.magenta) #}
regular5=c099ff
# {# replace_color_foot(theme.colors.cyan) #}
regular6=86e1fc
# {# replace_color_foot(theme.colors.white) #}
regular7=828bb8
# {# replace_color_foot(theme.colors.bright_black) #}
bright0=444a73
# {# replace_color_foot(theme.colors.bright_red) #}
bright1=ff8d94
# {# replace_color_foot(theme.colors.bright_green) #}
bright2=c7fb6d
# {# replace_color_foot(theme.colors.bright_yellow) #}
bright3=ffd8ab
# {# replace_color_foot(theme.colors.bright_blue) #}
bright4=9ab8ff
# {# replace_color_foot(theme.colors.bright_magenta) #}
bright5=caabff
# {# replace_color_foot(theme.colors.bright_cyan) #}
bright6=b2ebff
# {# replace_color_foot(theme.colors.bright_white) #}
bright7=c8d3f5
