font=monospace:size=13
pad=8x0
box-drawings-uses-font-glyphs=no

[tweak]
overflowing-glyphs=no
# render-timer=osd

[scrollback]
lines=10000
# multiplier=20.0
indicator-position=none

[cursor]
style=Beam
# beam-thickness=1.1

[key-bindings]
search-start=Control+Shift+h
scrollback-up-line=Control+d 
scrollback-down-line=Control+f
# scrollback-down-line=Control+f Control+Shift+f

[search-bindings]
cursor-left=Left Control+h
cursor-right=Right Control+l
find-prev=Control+d
find-next=Control+f 

[url]
launch=handlr open ${url}
label-letters=abcdefghijklmnopqrstuvwxyz;,.[]

[colors]
cursor=111111 cccccc 
alpha=0.69
# {# replace_color_foot(theme.colors.background) #}
background=1e1e2e
# {# replace_color_foot(theme.colors.foreground) #}
foreground=cdd6f4
# {# replace_color_foot(theme.colors.black) #}
regular0=45475a
# {# replace_color_foot(theme.colors.red) #}
regular1=f38ba8
# {# replace_color_foot(theme.colors.green) #}
regular2=a6e3a1
# {# replace_color_foot(theme.colors.yellow) #}
regular3=f9e2af
# {# replace_color_foot(theme.colors.blue) #}
regular4=89b4fa
# {# replace_color_foot(theme.colors.magenta) #}
regular5=f5c2e7
# {# replace_color_foot(theme.colors.cyan) #}
regular6=94e2d5
# {# replace_color_foot(theme.colors.white) #}
regular7=bac2de
# {# replace_color_foot(theme.colors.bright_black) #}
bright0=585b70
# {# replace_color_foot(theme.colors.bright_red) #}
bright1=f38ba8
# {# replace_color_foot(theme.colors.bright_green) #}
bright2=a6e3a1
# {# replace_color_foot(theme.colors.bright_yellow) #}
bright3=f9e2af
# {# replace_color_foot(theme.colors.bright_blue) #}
bright4=89b4fa
# {# replace_color_foot(theme.colors.bright_magenta) #}
bright5=f5c2e7
# {# replace_color_foot(theme.colors.bright_cyan) #}
bright6=94e2d5
# {# replace_color_foot(theme.colors.bright_white) #}
bright7=a6adc8
