[default] #any displayname usr hyprctl monitors
path = "/home/zwind/background/img"
duration = "30m"
sorting = "random" # ascending descending random
mode = "center" # fit fit-border-color stretch tile center
queue-size = 15 # queue-size > number of available images in the folder. only work condition
initial-transition = true
recursive = false

# [default.transition.mosaic]
[default.transition.directional-wipe]
direction = [-1.0, 1.0]

