# Main bg
theme[main_bg]="#1f1f1f"

# Main text color
theme[main_fg]="#d4d4d4"

# Title color for boxes
theme[title]="#d4d4d4"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#569cd6"

# Background color of selected item in processes box
theme[selected_bg]="#1f1f1f"

# Foreground color of selected item in processes box
theme[selected_fg]="#f1e9d2"

# Color of inactive/disabled text
theme[inactive_fg]="#56b6c2"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#569cd6"

# Cpu box outline color
theme[cpu_box]="#56b6c2"

# Memory/disks box outline color
theme[mem_box]="#56b6c2"

# Net up/down box outline color
theme[net_box]="#56b6c2"

# Processes box outline color
theme[proc_box]="#56b6c2"

# Box divider line and small boxes line color
theme[div_line]="#56b6c2"

# Temperature graph colors
theme[temp_start]="#6a9955"
theme[temp_mid]="#dcdcaa"
theme[temp_end]="#f44747"

# CPU graph colors
theme[cpu_start]="#6a9955"
theme[cpu_mid]="#dcdcaa"
theme[cpu_end]="#f44747"

# Mem/Disk free meter
theme[free_start]="#6a9955"
theme[free_mid]="#dcdcaa"
theme[free_end]="#f44747"

# Mem/Disk cached meter
theme[cached_start]="#6a9955"
theme[cached_mid]="#dcdcaa"
theme[cached_end]="#f44747"

# Mem/Disk available meter
theme[available_start]="#6a9955"
theme[available_mid]="#dcdcaa"
theme[available_end]="#f44747"

# Mem/Disk used meter
theme[used_start]="#6a9955"
theme[used_mid]="#dcdcaa"
theme[used_end]="#f44747"

# Download graph colors
theme[download_start]="#6a9955"
theme[download_mid]="#dcdcaa"
theme[download_end]="#f44747"

# Upload graph colors
theme[upload_start]="#6a9955"
theme[upload_mid]="#dcdcaa"
theme[upload_end]="#f44747"
