require("utils.lazyload").on_vim_enter(function()
  vim.pack.add({
    { src = "https://github.com/folke/which-key.nvim" },
  })

  vim.o.timeout = true
  vim.o.timeoutlen = 100

  require("which-key").setup({
    preset = false,
    win = {
      width = { min = 30, max = 60 },
      height = { min = 4, max = 0.75 },
      padding = { 0, 1 },
      col = 1,
      row = -1,
      border = "rounded",
      title = true,
      title_pos = "center",
      no_overlap = true,
    },
    layout = { spacing = 3, width = { min = 30 } },
    keys = {
      scroll_down = "<c-f>",
      scroll_up = "<c-d>",
    },
    icons = {
      breadcrumb = "»",
      separator = "➜",
      group = "+",
      ellipsis = "…",
      mappings = true,
      rules = {},
      colors = true,
      keys = {
        Up = "",
        Down = "",
        Left = "",
        Right = "",
        C = "󰘴",
        M = "󰘵",
        D = "󰘳",
        S = "󰘶",
        CR = "󰌑",
        Esc = "󱊷",
        ScrollWheelDown = "󱕐",
        ScrollWheelUp = "󱕑",
        NL = "󰌑",
        BS = "󰁮",
        Space = "󱁐",
        Tab = "󰌒 ",
        F1 = "󱊫",
        F2 = "󱊬",
        F3 = "󱊭",
        F4 = "󱊮",
        F5 = "󱊯",
        F6 = "󱊰",
        F7 = "󱊱",
        F8 = "󱊲",
        F9 = "󱊳",
        F10 = "󱊴",
        F11 = "󱊵",
        F12 = "󱊶",
      },
    },
    triggers = {
      { "<leader>", mode = { "n", "v" } },
      { "g", mode = { "n", "v" } },
    },
    plugins = {
      marks = false,
      registers = false,
      spelling = { enabled = false },
      presets = {
        operators = false,
        motions = false,
        text_objects = false,
        windows = false,
        nav = false,
        g = false,
        z = false,
      },
    },
    show_help = false,
    show_keys = false,
    debug = false,
    spec = {
      {
        -- { "gi", desc = "Go To Last Insert", icon = { icon = "󰑆 ", color = "orange" } },
        { "gv", desc = "Last Visual Selection", icon = { icon = "󱊃 ", color = "orange" } },
        { "gb", desc = "Comment Toggle Block" },
        { "gc", desc = "Comment Toggle Line" },
        { "gbc", desc = "Comment Toggle Current Block" },
        { "gcA", desc = "Comment Insert End Of Line" },
        { "gcc", desc = "Comment Toggle Current Line" },
        { "gco", desc = "Comment Insert Below" },
        { "gcO", desc = "Comment Insert Above" },
        { "gn", icon = { icon = " ", color = "orange" } },
        -- { "<leader>l", icon = { icon = "󰒲 ", color = "grey" } },
        { "<leader>t", icon = { icon = "󰔎 ", color = "orange" } },
        { "<leader>e", icon = { icon = " ", color = "yellow" } },
        { "<leader>j", icon = { icon = "󰑆 ", color = "orange" } },
        { "<leader>ff", icon = { icon = " ", color = "orange" } },
        { "<leader>fo", icon = { icon = " ", color = "blue" } },
        { "<leader>fb", icon = { icon = " ", color = "grey" } },
        { "<leader>fe", icon = { icon = "󰱨 ", color = "yellow" } },
        { "<leader>fz", icon = { icon = "󱡠 ", color = "green" } },
        { "<leader>fr", icon = { icon = "󰆒 ", color = "green" } },
        -- { "rh", icon = { icon = " ", color = "orange" } },
        -- { "rq", icon = { icon = "󰈆  ", color = "red" } },
        -- { "rr", icon = { icon = " ", color = "yellow" } },
        -- { "rc", desc = "Toggle Show Command", icon = { icon = " ", color = "yellow" } },
      },
      {
        mode = { "v" },
        { "gb", desc = "Comment Toggle Block" },
        { "gc", desc = "Comment Toggle Line" },
      },
      {
        mode = { "n", "v" },
        { "<leader>b", group = "Buffer", icon = { icon = " ", color = "orange" } },
        { "<leader>f", group = "Find/File" },
        { "<leader>w", group = "Window" },
        -- { "<leader>s", group = "Session" },
        { "z", hidden = true },
        { "[", hidden = true },
        { "]", hidden = true },
        { "<c-w>", hidden = true },
        { "gx", desc = "Open {} Under Cursor", icon = { icon = "󰌻 ", color = "orange" } },
        -- { "g~", desc = "Toggle Case" },
        { "gt", icon = { icon = " ", color = "orange" } },
      },
    },
  })
end)
