theme = "default"

[background]
mode = "file"
path = "~/background/img/back10.jpg"
blur_radius = 0
dim_strength = 32

[battery]
enabled = false

[weather]
enabled = true
location = "ChangSha"

[now_playing]
include_players = ["mpv", "mpd", "zen"]

[visuals.avatar]
image_path = "/home/zwind/background/avatar.png"
# size = 150
# x = 0
# y = -120

[visuals.clock]
font_family = "JetBrainsMono NFM"
font_weight = 700
font_style = "normal"
# color = "#FFFFFFB0"

[visuals.date]
font_family = "JetBrainsMono NFM"
# color = "#FFFFFFA0"

[visuals.input]
font_family = "JetBrainsMono NFM"
background_color = "rgba(255, 255, 255, 0.15)"

[visuals.username]
text = "Z_wind"
font_size = 39
font_family = "TypoGraphica"

[visuals.weather.icon]
size = 40
opacity = 80
halign = "left"
valign = "bottom"
x = 40
y = -108

[visuals.weather.temperature]
font_family = "TypoGraphica"

[visuals.weather.location]
font_style = "italic"
font_family = "JetBrainsMono NFM"

[visuals.now_playing]
enabled = true
fade_duration_ms = 320

[visuals.now_playing.artwork]
size = 59
radius = 8
opacity = 90
halign = "left"
valign = "center"
x = 0
y = 0
relative_to = "now_playing"

[visuals.now_playing.artist]
width = 318
color = "rgba(255, 255, 255, 0.39)"
font_family = "LXGW WenKai Mono GB Screen"
font_size = 16
font_weight = 400
halign = "left"
valign = "top"
x = 65
y = 10
relative_to = "now_playing"

[visuals.now_playing.title]
width = 318
color = "rgba(255, 255, 255, 0.69)"
font_family = "LXGW WenKai Mono GB Screen"
font_size = 16
font_weight = 400
halign = "left"
valign = "bottom"
x = 65
y = -10
relative_to = "now_playing"
